services:
  mongodb:
    image: mongo
    command: ['--replSet', 'rs0', '--bind_ip_all']
    volumes:
      - ./tools/backup:/usr/dump
      - mongodb_data:/data/db
    ports:
      - '27017:27017'
    healthcheck:
      test: |
        mongosh --eval "try { rs.status().ok } catch(e) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }] }).ok }"
      interval: 5s
      timeout: 30s
      start_period: 10s
      retries: 30

volumes:
  mongodb_data:
